### ISSUE TITLE
Composer install requirements

### ISSUE THREAD

**Issue by matthewnw** [netsensei/europeana#1]
Would you be able to update the composer requirements to be less rigid?

    "guzzlehttp/guzzle": "6.1.0",
    "doctrine/collections": "1.3"

As I am using Laravel, Guzzle and Doctrine are already included and will not install lower versions fixed. Could they be changed to something like:

    "guzzlehttp/guzzle": "^6.1.0",
    "doctrine/collections": "^1.3"

Thanks

**Comment by netsensei** [comment]
Yup. Unless Guzzle introduced some serious changes to their api, I don't think it should have that big an impact here. Just need to make sure the tests stay green.

**Comment by netsensei** [comment]
Okay. I made the change. Latest versions I get:

```
  - Updating guzzlehttp/guzzle (6.1.0 => 6.3.0)
    Checking out f4db5a78a5ea468d4831de7f0bf9d9415e348699
  - Updating doctrine/collections (v1.3.0 => v1.5.0)
    Checking out a01ee38fcd999f34d9bfbcee59dbda5105449cbf
```

I ran my tests, everything just works fine. Pushed as a 1.0.0 release (I didn't do releases, I noticed. :-)

Just let me know if this works for you, I'll close the issue.

**Comment by matthewnw** [comment]
Awesome thanks for the speedy response. How long until the Packagist repo updates do you think?

**Comment by netsensei** [comment]
Allright. I just give it manual poke. It's at 1.0.1 now. I did a second patch release because hhvm tests were breaking (and they aren't that relevant)

**Comment by matthewnw** [comment]
Works great thanks! One thing I noticed in the documentation is it says

    $payload = new SearchPayload();
    $payload->addQuery($query);

But it should be `$payload->setQuery($query);`.
